### ISSUE TITLE
disabling ADR leads to Typeerror exception

### ISSUE THREAD

**Issue by mzemb** [Fluent-networks/floranet#2]
Hi.

I've set adrenable = False in the config file, and I'm getting an exception when starting floranet:

> 
> [Floranet#info] Initialising the server
> [Floranet#info] Starting the server
> [twisted.internet.defer#critical] Unhandled error in Deferred:
> [twisted.internet.defer#critical] 
> 	Traceback (most recent call last):
> 	  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.6.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 194, in start
> 	    self()
> 	  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.6.0-py2.7-linux-x86_64.egg/twisted/internet/task.py", line 239, in __call__
> 	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
> 	  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.6.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 150, in maybeDeferred
> 	    result = f(*args, **kw)
> 	  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.6.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1445, in unwindGenerator
> 	    return _inlineCallbacks(None, gen, Deferred())
> 	--- <exception caught here> ---
> 	  File "/usr/local/lib/python2.7/dist-packages/Twisted-16.6.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1299, in _inlineCallbacks
> 	    result = g.send(result)
> 	  File "/home/gl/floranet/floranet/netserver.py", line 284, in _processADRRequests
> 	    returnValue()
> 	exceptions.TypeError: returnValue() takes exactly 1 argument (0 given)

I have difficulties understanding the issue since I don't know twisted.

Thank you,

M.

**Comment by frankedwards** [comment]
Hi Michael

Thank you for flagging this issue, I see the same problem.... I will look into it.

Also thanks for the PR for the EU868 band.

Regards

Frank

**Comment by frankedwards** [comment]
Hi

As indicated, the bug is that ReturnValue() is not passed an argument in _processADRRequests(). However, I think the scheduled task should not be called if adrenable is false. I have altered start() to reflect this.

Can you see if https://github.com/Fluent-networks/floranet/commit/d645e28b8b2fcb9e2119c33c8a4b0d2df313d7a9 works for you.

**Comment by mzemb** [comment]
Hello.

I confirm that the issue is fixed (tested in 0.3.3 , 4c52a7 ), thank you.

Regards,

Michael
