### ISSUE TITLE
missing 8 of 16 bytes payload

### ISSUE THREAD

**Issue by mzemb** [Fluent-networks/floranet#3]
Hi.

I'm currently testing floranet with loramotes that send 16 bytes of payload, and I'm only receiving the first 8 bytes (in AppServerInterface.netServerReceiver() ).

I investigated a little and I suspect that the culprit is in MacDataMessage.ecrypt() (in lora_mac.py).
If I understood correctly, k is the number of time we have 16 bytes in the packet, but the xor unpacking is done on 8 bytes. So I changed the line
`for i in range (k):`
to
`for i in range (k*2):`

It solves my problem, and my application now receives the 16 bytes. However, as I'm not confident at all and with no other test abilities than my setup I wanted your opinion on the change.

Regards,

Michael

**Comment by frankedwards** [comment]
Hi Michael

Yes I see that issue and your fix is fine. The encrypt() unit tests had only used a 1 byte payload for testing, I have now expanded that to test other payload length cases. 

I am working on a number of other changes & enhancements, and I will include this fix in the next release.

**Comment by mzemb** [comment]
Sweet.

In the changes you are talking about, is there anything concerning downlink messages ? I have difficulties getting it to work, but I suspect the problem to be in the end device.

**Comment by frankedwards** [comment]
Hi

I have had issues to do with downlink messages, but I have determined them to be with the gateway, specifically the packet forwarder process. What is your gateway setup?

Do you see downlink messages (PULL_RESP) exiting the server in the log, e.g.:
2017-02-18T09:43:29+1000 [Floranet#info] Sending PULL_RESP message to 192.168.1.125:35123
2017-02-18T09:43:29+1000 [Floranet#info] Sending '\x01\x00\x00\x03{"txpk":{"imme":true,"freq":923.9,"rfch":0,"powe":26,"modu":"LORA","datr":"SF10BW500","codr":"4/5","ipol":true,"size":24,"data":"YAAAEAaAAAAPUkCrndWbp9UKyewg553F","ncrc":false}}' to 192.168.1.125:35123

**Comment by mzemb** [comment]
Hi.

Thank you for your help.
My gateway is a kerlink , running the basic packet forwarder.
I can indeed see the downlink message exiting the server and being send by the gateway, which led me to think that  the issue is with my end device, but I haven't had the time to investigate right now as I have been working on another urgent matter.

I'll let you know in a few days how it turns out when I'll have the opportunity to work on the subject.

Regards,

Michael

**Comment by frankedwards** [comment]
Hi Michael

No worries. The issue I found was to do with downlink scheduling. Specifically, sending a response to the gateway results in head-of-line blocking for other responses. However, this can only occur with 2 or more active devices.

Semtech have now implemented smarter downlink scheduling in their packet forwarder. Have a look at the section "Just in Time Scheduling" here:
https://github.com/Lora-net/packet_forwarder/blob/master/lora_pkt_fwd/readme.md

**Comment by frankedwards** [comment]
Closing.
